version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - NODE_ENV=development

  db:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_DATABASE: '19070001035_izzetcemibik_midtermdatabase'
      MYSQL_USER: 'midtermizzetcemibik'
      MYSQL_PASSWORD: '12345Izo'
      MYSQL_ROOT_PASSWORD: '12345Izo'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
